In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Step 1: Import Libraries

In [2]:
# Import Libraries

import time
import pickle
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
from numpy import mean
from sklearn.svm import SVC
from sklearn.metrics import auc
from collections import Counter
warnings.simplefilter("ignore")
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
from sklearn import preprocessing
from prettytable import PrettyTable 
from sklearn.metrics import roc_curve
from astropy.table import Table, Column
from imblearn.over_sampling import SMOTE
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score

from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

###### SMOTE and RandomUnderSampler (for balancing data) ############

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline

from imblearn.over_sampling import SVMSMOTE 
from imblearn.over_sampling import ADASYN 
from imblearn.under_sampling import NearMiss 

# Step 2: Read Dataset

In [3]:
# Load Dataset

data = pd.read_excel('drive/My Drive/Colab Notebooks/WisconsinDataset/Forms_cleaned.xlsx', 'form1')

print('\n\nDataset:')
print('========\n')
data



Dataset:



EID FormID  Flagged  Attempt  ...  idur.167  idur.168  idur.169  idur.170
0     e100001  form1        0        5  ...        53        82       100        21
1     e100002  form1        1        1  ...       120        93        87        29
2     e100003  form1        1        1  ...        63        96        79        48
3     e100004  form1        1        3  ...        59        41        84        17
4     e100005  form1        1        5  ...       164        74        63        17
...       ...    ...      ...      ...  ...       ...       ...       ...       ...
1631  e101632  form1        0        1  ...        56        47        61        19
1632  e101633  form1        0        1  ...        79        59        48        40
1633  e101634  form1        0        1  ...        19        27        43        14
1634  e101635  form1        0        1  ...        18       109        94        14
1635  e101636  form1        0        1  ...        28        51        45        46

[1636 rows x 515 columns]

# Step 3: Understand Datset

In [4]:
# Understand Dataset

print("\n\nAttributes of Dataset:")
print("======================\n")

print("\nName of Dataset: Forms_cleaned")
print("==============================\n")

print("\nNumber of Rows:", len(data))
print("====================\n")

print("\nNumber of Columns:", len(data.columns))
print("======================\n")

print("\nClass Distribution:")
print("===================\n")
print(data['Flagged'].value_counts())



Attributes of Dataset:


Name of Dataset: Forms_cleaned


Number of Rows: 1636


Number of Columns: 515


Class Distribution:

0    1590
1      46
Name: Flagged, dtype: int64


# Step 4: Pre-Process Dataset

In [5]:
# Pre-Processing

data.tail()
data.drop(data.loc[:, 'iresp.1':'iresp.170'], inplace = True, axis = 1) 
data_final = data

In [6]:
# Count Null Values

print(data_final.isnull().sum())
print(data_final.shape)

EID         0
FormID      0
Flagged     0
Attempt     0
tot_time    0
           ..
idur.166    0
idur.167    0
idur.168    0
idur.169    0
idur.170    0
Length: 345, dtype: int64
(1636, 345)


In [7]:
# Time

data_final['mean_idur'] = data_final.loc[:, 'idur.1':'idur.170'].mean(axis=1)
data_final['median_idur'] = data_final.loc[:, 'idur.1':'idur.170'].median(axis=1)
data_final['max_idur'] = data_final.loc[:, 'idur.1':'idur.170'].max(axis=1)
data_final['min_idur'] = data_final.loc[:, 'idur.1':'idur.170'].min(axis=1)

# Correct Answers

data_final['iraw_score'] = data_final.loc[:, 'iraw.1':'iraw.170'].sum(axis=1)
data_final['iraw_score_pct'] = data_final['iraw_score']/170
data_final

EID FormID  Flagged  ...  min_idur  iraw_score  iraw_score_pct
0     e100001  form1        0  ...        14          54        0.317647
1     e100002  form1        1  ...        11          55        0.323529
2     e100003  form1        1  ...        16          61        0.358824
3     e100004  form1        1  ...        12          61        0.358824
4     e100005  form1        1  ...         0          62        0.364706
...       ...    ...      ...  ...       ...         ...             ...
1631  e101632  form1        0  ...         8         156        0.917647
1632  e101633  form1        0  ...         7         153        0.900000
1633  e101634  form1        0  ...         7         154        0.905882
1634  e101635  form1        0  ...        10         152        0.894118
1635  e101636  form1        0  ...        10         156        0.917647

[1636 rows x 351 columns]

# Step 5: Feature Selection

In [8]:
# iraw_idur_OEF (both+OEF)

col_features = ['Attempt', 'tot_time', 'mean_idur', 'median_idur', 'max_idur', 'min_idur', 'iraw_score_pct']

for x in range(1,171):
    col_features.append('idur.'+str(x))

for i in range(1,171):
    col_features.append('iraw.'+str(i))

X = data_final.loc[:, col_features]
Y = data_final.Flagged    

### Outliers

In [9]:
# Import Libraries
from sklearn.ensemble import IsolationForest

# Identify outliers in the training dataset
Isolation_Forest = IsolationForest(random_state=64)
outlier1 = Isolation_Forest.fit_predict(X)

print("\n\nOutliers Detected by Isolation Forest:")
print("======================================\n")
print(outlier1)

print("\n\nNumber Outliers Detected: ", list(outlier1).count(-1))
print("\n\nOther 1: ", list(outlier1).count(1))
print("==============================\n")



Outliers Detected by Isolation Forest:

[-1 -1 -1 ...  1  1  1]


Number Outliers Detected:  176


Other 1:  1460



In [10]:
# Import Libraries
from sklearn.covariance import EllipticEnvelope

# Identify outliers in the training dataset
Elliptic_Envelope = EllipticEnvelope()
outlier2 = Elliptic_Envelope.fit_predict(X)

print("\n\nOutliers Detected by EllipticEnvelope:")
print("======================================\n")
print(outlier2)

print("\n\nNumber Outliers Detected: ", list(outlier2).count(-1))
print("\n\nOther 1: ", list(outlier2).count(1))
print("==============================\n")



Outliers Detected by EllipticEnvelope:

[1 1 1 ... 1 1 1]


Number Outliers Detected:  164


Other 1:  1472



In [11]:
# Import Libraries
from sklearn.neighbors import LocalOutlierFactor

# Identify outliers in the training dataset
Local_Outlier_Factor = LocalOutlierFactor()
outlier3 = Local_Outlier_Factor.fit_predict(X)

print("\n\nOutliers Detected by LocalOutlierFactor:")
print("========================================\n")
print(outlier3)

print("\n\nNumber Outliers Detected: ", list(outlier3).count(-1))
print("\n\nOther 1: ", list(outlier3).count(1))
print("==============================\n")



Outliers Detected by LocalOutlierFactor:

[1 1 1 ... 1 1 1]


Number Outliers Detected:  33


Other 1:  1603



In [12]:
# Import Libraries
from sklearn.svm import OneClassSVM

# Identify outliers in the training dataset
One_Class_SVM = OneClassSVM(kernel='linear', tol=0.001, nu=0.05)
outlier4 = One_Class_SVM.fit_predict(X)

print("\n\nOutliers Detected by OneClassSVM:")
print("=================================\n")
print(outlier4)

print("\n\nNumber Outliers Detected: ", list(outlier4).count(-1))
print("\n\nOther 1: ", list(outlier4).count(1))
print("==============================\n")



Outliers Detected by OneClassSVM:

[1 1 1 ... 1 1 1]


Number Outliers Detected:  81


Other 1:  1555



In [13]:
# Import Libraries
from sklearn.cluster import DBSCAN

# Identify outliers in the training dataset
outlier_detection = DBSCAN(min_samples = 1000, eps = 2500)

outlier5 = outlier_detection.fit_predict(X)

print("\n\nOutliers Detected by DBSCAN:")
print("============================\n")
print(outlier5)

print("\n\nNumber Outliers Detected: ", list(outlier5).count(-1))
print("\n\nOther 0: ", list(outlier5).count(0))
print("==============================\n")



Outliers Detected by DBSCAN:

[0 0 0 ... 0 0 0]


Number Outliers Detected:  77


Other 0:  1559



In [14]:
# Adding Outliers Scores

data_final["Outliers_Score1"] = outlier1
data_final["Outliers_Score2"] = outlier2
data_final["Outliers_Score3"] = outlier3
data_final["Outliers_Score4"] = outlier4
data_final["Outliers_Score5"] = outlier5

print("\n\ndata_final After Adding Outliers Scores: ")
print("===============================================\n")
data_final



data_final After Adding Outliers Scores: 



EID FormID  ...  Outliers_Score4  Outliers_Score5
0     e100001  form1  ...                1                0
1     e100002  form1  ...                1                0
2     e100003  form1  ...                1                0
3     e100004  form1  ...                1                0
4     e100005  form1  ...                1                0
...       ...    ...  ...              ...              ...
1631  e101632  form1  ...                1                0
1632  e101633  form1  ...                1                0
1633  e101634  form1  ...                1                0
1634  e101635  form1  ...                1                0
1635  e101636  form1  ...                1                0

[1636 rows x 356 columns]

In [15]:
# summatives and top features from 4 selection algorithm

col_features = ['Attempt', 'tot_time', 'mean_idur', 'median_idur', 'max_idur', 'min_idur', 'iraw_score_pct', 'iraw.32', 'iraw.77', 'iraw.147', 'iraw.57', 'iraw.86', 'iraw.152', 'iraw.12', 'iraw.127', 'iraw.140', 'iraw.96', 'idur.146', 'idur.36', 'idur.114', 'idur.84', 'idur.142', 'idur.60', 'idur.71', 'idur.133', 'idur.88', 'idur.59', 'idur.69', 'idur.38', 'idur.67', 'idur.81', 'idur.96', 'idur.162', 'Outliers_Score1', 'Outliers_Score2', 'Outliers_Score3', 'Outliers_Score4', 'Outliers_Score5']

X = data_final.loc[:, col_features]
Y = data_final.Flagged    

In [16]:
# Count Values

counter = Counter(Y)
print(counter)

Counter({0: 1590, 1: 46})


# Step 7: Feature Scaling

In [17]:
# Import Libraries
from sklearn.preprocessing import MinMaxScaler
num_cols = X.columns

# apply standardization on numerical features
for i in num_cols:
    # fit on training data column
    scale = MinMaxScaler(feature_range=(0, 1)).fit(X[[i]])

    # transform the training data column
    X[i] = scale.transform(X[[i]])
    
print("\n\nTraining Features After Scaling: ")
print("=================================\n")
X



Training Features After Scaling: 



Attempt  tot_time  ...  Outliers_Score4  Outliers_Score5
0         1.0  0.251140  ...              1.0              1.0
1         0.2  0.373250  ...              1.0              1.0
2         0.2  0.375825  ...              1.0              1.0
3         0.6  0.318526  ...              1.0              1.0
4         1.0  0.440850  ...              1.0              1.0
...       ...       ...  ...              ...              ...
1631      0.2  0.177477  ...              1.0              1.0
1632      0.2  0.274478  ...              1.0              1.0
1633      0.2  0.375396  ...              1.0              1.0
1634      0.2  0.147916  ...              1.0              1.0
1635      0.2  0.207039  ...              1.0              1.0

[1636 rows x 38 columns]

# Step 8: Automatic Features Selection

<div class="alert alert-info">
<b>4 Automatic Features Selection Methods:</b>
<div class="alert alert-success">
<b>
    <code>(1)</code> Chi2 Features Selection <br><br>
    <code>(2)</code> ExtraTree Features Selection <br><br>
    <code>(3)</code> REF Features Selection <br><br>
    <code>(4)</code> Pearson Correlation Features Selection <br><br>
</b>
</div>
</div>

## Step 8.1: Chi2 Features Selection

## Step 8.2: Extra Tree Features Selection

<div class="alert alert-warning">
<b>This class implements a meta estimator that fits a number of randomized decision trees (a.k.a. extra-trees) on various sub-samples of the dataset and uses averaging to improve the predictive accuracy and control over-fitting.</b>
</div>

In [18]:
# Import Libraries
# from sklearn.ensemble import ExtraTreesClassifier

# model = ExtraTreesClassifier()
# model.fit(X,Y)
# columns = X.columns.values

# print(model.feature_importances_)
# feat_importances = pd.Series(model.feature_importances_)

In [19]:
# Print 20 Best Features

# top = feat_importances.nlargest(20)
# feature = top.index
# names = columns[feature]

# top_features = pd.DataFrame()
# top_features["Features"]=names
# top_features["    Score"]=top.values
# top_features["Ranking"] = ["       --->      Rank-01","       --->      Rank-02","       --->      Rank-03","       --->      Rank-04","       --->      Rank-05","       --->      Rank-06","       --->      Rank-07","       --->      Rank-08","       --->      Rank-09","       --->      Rank-10","       --->      Rank-11","       --->      Rank-12","       --->      Rank-13","       --->      Rank-14","       --->      Rank-15","       --->      Rank-16","       --->      Rank-17","       --->      Rank-18","       --->      Rank-19","       --->      Rank-20"]
# print("\n===================================================\n")
# print("================== TOP 10 FEATURES ================")
# print("\n===================================================\n")
# print(top_features.to_string(index=False))
# print("\n===================================================\n")

### Features Set-2

In [20]:
# Features_Set2 = X[top_features["Features"]]

# print("\n\nAutomatic Selected Features Set 2:")
# print("==================================\n")
# Features_Set2

### Outliers

In [21]:
# Import Libraries
from sklearn.ensemble import IsolationForest

# Identify outliers in the training dataset
Isolation_Forest = IsolationForest(random_state=64)
outlier1 = Isolation_Forest.fit_predict(X)

print("\n\nOutliers Detected by Isolation Forest:")
print("======================================\n")
print(outlier1)

print("\n\nNumber Outliers Detected: ", list(outlier1).count(-1))
print("\n\nOther 1: ", list(outlier1).count(1))
print("==============================\n")



Outliers Detected by Isolation Forest:

[-1  1 -1 ...  1  1  1]


Number Outliers Detected:  217


Other 1:  1419



<center>
    <br>
        <br>
            <br>
                <h5 style = "color:blue">====================================================================</h5>
                <h2 style = "color:green">Training Phase</h2>
                <h5 style = "color:blue">====================================================================</h5>
            <br>
        <br>
    <br>
</center>

# Step 12: Train Models of Features Set-4

## Step 12.1: Train Test Split

In [22]:
# Train Test Split

#X_train, X_test, y_train, y_test= train_test_split(Features_Set2, Y, test_size= 0.2, random_state=64 ,shuffle = True)

##### top 20 features by 1 selection alg. #########
# X_train, X_test, y_train, y_test= train_test_split(Features_Set2, Y, test_size= 0.2, random_state=23 ,shuffle = True)
# X_train1, X_pred_train, y_train1, y_pred_train= train_test_split(X_train, y_train, test_size= 0.25, random_state=23 ,shuffle = True)

##### top features from 4 selection alg. plus summatives ##########
# X_train, X_test, y_train, y_test= train_test_split(X, Y, test_size= 0.2, random_state=23 ,shuffle = True)
# X_train1, X_pred_train, y_train1, y_pred_train= train_test_split(X_train, y_train, test_size= 0.25, random_state=23 ,shuffle = True)


##### top features from 4 selection alg. plus summatives, and resampling ##########
### both 33%
#over = SMOTE(sampling_strategy=0.4)
over = SVMSMOTE(sampling_strategy=0.4, random_state=42, k_neighbors=10)
#over = ADASYN(sampling_strategy=0.4, random_state=42)  ###bad

#under = RandomUnderSampler(sampling_strategy=0.5)
under = NearMiss(sampling_strategy=1)

steps = [('o', over), ('u', under)]

pipeline = Pipeline(steps=steps)

X_train, X_test, y_train, y_test= train_test_split(X, Y, test_size= 0.2, random_state=23 ,shuffle = True)
X_train1_orig, X_pred_train, y_train1_orig, y_pred_train= train_test_split(X_train, y_train, test_size= 0.25, random_state=23 ,shuffle = True)

X_train1, y_train1 = pipeline.fit_resample(X_train1_orig, y_train1_orig)


## Step 12.3: Random Forest Classifier

In [23]:
# Training

clf1 = RandomForestClassifier(criterion="gini", max_depth=500, max_features="auto", min_samples_leaf=1, min_samples_split=2, n_estimators=911)
clf1.fit(X_train1, y_train1)

RandomForestClassifier(max_depth=500, n_estimators=911)

### Evalute the performace

In [24]:
# Predictions
y_pred = clf1.predict(X_pred_train)


tn, fp, fn, tp = confusion_matrix(y_pred_train, y_pred).ravel()
fpr = (fp)/(fp+tn)
real_cheater = tp+fn

print("  precision: ", precision_score(y_pred_train, y_pred))
print("  recall: ", recall_score(y_pred_train, y_pred))
print("  f1-score: ", f1_score(y_pred_train, y_pred))

print("  fpr: ", fpr)
print("  tn: ", tn)
print("  fp: ", fp)
print("  fn: ", fn)
print("  tp: ", tp)
print("  real_cheaters: ", real_cheater)

  precision:  0.625
  recall:  0.7142857142857143
  f1-score:  0.6666666666666666
  fpr:  0.009375
  tn:  317
  fp:  3
  fn:  2
  tp:  5
  real_cheaters:  7


## Step 12.6: Gradient Boosting Classifier

In [25]:
# Training

clf2 = GradientBoostingClassifier(learning_rate=0.1, n_estimators=100)
clf2.fit(X_train1, y_train1)


GradientBoostingClassifier()

### Evalute the performace

In [26]:
# Predictions
y_pred = clf2.predict(X_pred_train)

tn, fp, fn, tp = confusion_matrix(y_pred_train, y_pred).ravel()
fpr = (fp)/(fp+tn)
real_cheater = tp+fn

print("  precision: ", precision_score(y_pred_train, y_pred))
print("  recall: ", recall_score(y_pred_train, y_pred))
print("  f1-score: ", f1_score(y_pred_train, y_pred))

print("  fpr: ", fpr)
print("  tn: ", tn)
print("  fp: ", fp)
print("  fn: ", fn)
print("  tp: ", tp)
print("  real_cheaters: ", real_cheater)

  precision:  0.375
  recall:  0.42857142857142855
  f1-score:  0.39999999999999997
  fpr:  0.015625
  tn:  315
  fp:  5
  fn:  4
  tp:  3
  real_cheaters:  7


In [27]:
clf3 = MLPClassifier(activation="relu", learning_rate="invscaling", solver="adam")
clf3.fit(X_train1, y_train1)

# Predictions
y_pred = clf3.predict(X_pred_train)

tn, fp, fn, tp = confusion_matrix(y_pred_train, y_pred).ravel()
fpr = (fp)/(fp+tn)
real_cheater = tp+fn

print("  precision: ", precision_score(y_pred_train, y_pred))
print("  recall: ", recall_score(y_pred_train, y_pred))
print("  f1-score: ", f1_score(y_pred_train, y_pred))

print("  fpr: ", fpr)
print("  tn: ", tn)
print("  fp: ", fp)
print("  fn: ", fn)
print("  tp: ", tp)
print("  real_cheaters: ", real_cheater)

  precision:  0.17391304347826086
  recall:  0.5714285714285714
  f1-score:  0.26666666666666666
  fpr:  0.059375
  tn:  301
  fp:  19
  fn:  3
  tp:  4
  real_cheaters:  7


In [28]:
clf4 = GaussianNB(var_smoothing=6.579332246575682e-08)
clf4.fit(X_train1, y_train1)

# Predictions
y_pred = clf4.predict(X_pred_train)

tn, fp, fn, tp = confusion_matrix(y_pred_train, y_pred).ravel()
fpr = (fp)/(fp+tn)
real_cheater = tp+fn

print("  precision: ", precision_score(y_pred_train, y_pred))
print("  recall: ", recall_score(y_pred_train, y_pred))
print("  f1-score: ", f1_score(y_pred_train, y_pred))

print("  fpr: ", fpr)
print("  tn: ", tn)
print("  fp: ", fp)
print("  fn: ", fn)
print("  tp: ", tp)
print("  real_cheaters: ", real_cheater)

  precision:  0.14285714285714285
  recall:  0.2857142857142857
  f1-score:  0.19047619047619047
  fpr:  0.0375
  tn:  308
  fp:  12
  fn:  5
  tp:  2
  real_cheaters:  7


# Step 13: Combine Models with Stacking

In [29]:
# Prediction of all models
 #   model2 = StackingClassifier(estimators7, final_estimator=LogisticRegression() )
 #   model2 = StackingClassifier(estimators7, final_estimator=SVC(kernel='linear', probability=True))
 #   model2 = StackingClassifier(estimators7, final_estimator=GradientBoostingClassifier() )
 #   model2 = StackingClassifier(estimators7, final_estimator=RandomForestClassifier() )
  #   model2 = StackingClassifier(estimators7, final_estimator=DecisionTreeClassifier() )

P1 = clf1.predict_proba(X_pred_train)
P1 = P1[:, 1]
P2 = clf2.predict_proba(X_pred_train)
P2 = P2[:, 1]
P3 = clf3.predict_proba(X_pred_train)
P3 = P3[:, 1]
P4 = clf4.predict_proba(X_pred_train)
P4 = P4[:, 1]

P = [P1,P2,P3,P4]
P = np.transpose(P)
#combined_model = GradientBoostingClassifier()
combined_model = RandomForestClassifier()
combined_model.fit(P, y_pred_train)


RandomForestClassifier()

In [30]:
# scores on test data
###
y_pred = clf1.predict(X_test)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
fpr = (fp)/(fp+tn)
real_cheater = tp+fn

print("  -------------------- RF ------------------------- ")
print("  precision: ", precision_score(y_test, y_pred))
print("  recall: ", recall_score(y_test, y_pred))
print("  f1-score: ", f1_score(y_test, y_pred))

print("  fpr: ", fpr)
print("  tn: ", tn)
print("  fp: ", fp)
print("  fn: ", fn)
print("  tp: ", tp)
print("  real_cheaters: ", real_cheater)

###
y_pred = clf2.predict(X_test)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
fpr = (fp)/(fp+tn)
real_cheater = tp+fn

print("  -------------------- GB ------------------------- ")
print("  precision: ", precision_score(y_test, y_pred))
print("  recall: ", recall_score(y_test, y_pred))
print("  f1-score: ", f1_score(y_test, y_pred))

print("  fpr: ", fpr)
print("  tn: ", tn)
print("  fp: ", fp)
print("  fn: ", fn)
print("  tp: ", tp)
print("  real_cheaters: ", real_cheater)

###
y_pred = clf3.predict(X_test)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
fpr = (fp)/(fp+tn)
real_cheater = tp+fn

print("  -------------------- NN ------------------------- ")
print("  precision: ", precision_score(y_test, y_pred))
print("  recall: ", recall_score(y_test, y_pred))
print("  f1-score: ", f1_score(y_test, y_pred))

print("  fpr: ", fpr)
print("  tn: ", tn)
print("  fp: ", fp)
print("  fn: ", fn)
print("  tp: ", tp)
print("  real_cheaters: ", real_cheater)

###
y_pred = clf2.predict(X_test)

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
fpr = (fp)/(fp+tn)
real_cheater = tp+fn

print("  -------------------- NB ------------------------- ")
print("  precision: ", precision_score(y_test, y_pred))
print("  recall: ", recall_score(y_test, y_pred))
print("  f1-score: ", f1_score(y_test, y_pred))

print("  fpr: ", fpr)
print("  tn: ", tn)
print("  fp: ", fp)
print("  fn: ", fn)
print("  tp: ", tp)
print("  real_cheaters: ", real_cheater)

  -------------------- RF ------------------------- 
  precision:  0.9
  recall:  0.6
  f1-score:  0.7200000000000001
  fpr:  0.003194888178913738
  tn:  312
  fp:  1
  fn:  6
  tp:  9
  real_cheaters:  15
  -------------------- GB ------------------------- 
  precision:  0.75
  recall:  0.4
  f1-score:  0.5217391304347827
  fpr:  0.006389776357827476
  tn:  311
  fp:  2
  fn:  9
  tp:  6
  real_cheaters:  15
  -------------------- NN ------------------------- 
  precision:  0.5454545454545454
  recall:  0.4
  f1-score:  0.4615384615384615
  fpr:  0.01597444089456869
  tn:  308
  fp:  5
  fn:  9
  tp:  6
  real_cheaters:  15
  -------------------- NB ------------------------- 
  precision:  0.75
  recall:  0.4
  f1-score:  0.5217391304347827
  fpr:  0.006389776357827476
  tn:  311
  fp:  2
  fn:  9
  tp:  6
  real_cheaters:  15


In [31]:
P1_test = clf1.predict_proba(X_test)
P1_test = P1_test[:, 1]
P2_test = clf2.predict_proba(X_test)
P2_test = P2_test[:, 1]
P3_test = clf3.predict_proba(X_test)
P3_test = P3_test[:, 1]
P4_test = clf4.predict_proba(X_test)
P4_test = P4_test[:, 1]

P_test = [P1_test,P2_test,P3_test,P4_test]
P_test = np.transpose(P_test)

combined_model_predictions = combined_model.predict(P_test)

In [32]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [33]:
tn, fp, fn, tp = confusion_matrix(y_test, combined_model_predictions).ravel()
fpr = (fp)/(fp+tn)
real_cheater = tp+fn

print("  precision: ", precision_score(y_test, combined_model_predictions))
print("  recall: ", recall_score(y_test, combined_model_predictions))
print("  f1-score: ", f1_score(y_test, combined_model_predictions))

print("  fpr: ", fpr)
print("  tn: ", tn)
print("  fp: ", fp)
print("  fn: ", fn)
print("  tp: ", tp)
print("  real_cheaters: ", real_cheater)


  precision:  0.8571428571428571
  recall:  0.4
  f1-score:  0.5454545454545455
  fpr:  0.003194888178913738
  tn:  312
  fp:  1
  fn:  9
  tp:  6
  real_cheaters:  15
